language: r
r:
  - release
  - devel

sudo: false
cran: https://cran.r-project.org
warnings_are_errors: true

cache: packages

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev

r_github_packages:
  - r-lib/covr

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: always


env:
  global:
    - NOT_CRAN: true
    - R_BUILD_ARGS="--resave-data --compact-vignettes=gs+qpdf"
    - R_CHECK_ARGS="--as-cran --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"
